# Global Setting for the Database
# PageSize, StartRID, etc..


PAGE_SIZE = 4096
PAGE_RECORD_SIZE = 8
BASE_PAGE_COUNT = 16
META_COLUMN_COUNT = 4
ENTRIES_PER_PAGE = 512
ENTRIES_PER_PAGE_RANGE = 8192

INDIRECTION = 0 # int
RID_COLUMN = 1 # int
TIMESTAMP_COLUMN = 2 # datetime
SCHEMA_ENCODING_COLUMN = 3 # string
KEY_COLUMN = META_COLUMN_COUNT